### ISSUE TITLE
experimental:params cast_shadows tag not taking effect

### ISSUE THREAD

**Issue by ddengster** [ignitionrobotics/ign-gazebo#1010]
## Environment
* OS Version:  
Ubuntu 20.04

* Source or binary build? 
Source, 4->5 commit 0c401c17c1d4b748233c61921c47da5725ce9d5c

## Description
* Expected behavior: Using `<experimental:params>` and adding the `<cast_shadows>0</cast_shadows>` tag on visuals of an `<included>` model should make the model not cast a shadow
* Actual behavior: Model still casts shadows.

## Steps to reproduce

1. Edit this sdf file: https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo5/examples/worlds/import_mesh.sdf
2. add
```
<experimental:params>
  <visual element_id="link::visual">
    <cast_shadows action="add">0</cast_shadows>
  </visual>
</experimental:params>
```
under the `<include>` tag.
3. run `ign gazebo import_mesh.sdf`

--

Additionally, if you add `std::cout << includeSDFFirstElem->ToString("") << std::endl;` under this [LOC](https://github.com/ignitionrobotics/sdformat/blob/sdf11/src/parser.cc#L1491) it will print out the combined `<cast_shadows>` tags correctly under `<visual>`

**Comment by chapulina** [comment]
Should be fixed as of #1015. Merging forward soon.
