### ISSUE TITLE
Import an image bug

### ISSUE THREAD

**Issue by Kakcalu13** [ignitionrobotics/ign-gazebo#1036]
System information:
- Ign Citadel on Ubuntu 20.04 Focal
- Ros2 Foxy (Doubt this has to do with anything) 

Problem: I'm not sure if this is the bug because I followed almost everything even on the gazebo classic tutorials. I'm starting to believe it's a bug. Please close this if it's not a bug. 

I wrote a full information on this [question](https://answers.gazebosim.org/question/27379/how-to-add-an-image-as-ground-plane-in-citadel/)

**Comment by chapulina** [comment]
I answered the question on Gazebo Answers, this isn't a bug, so closing.
