### ISSUE TITLE
Is it possible to simulate flexible objects such as ropes and cables?

### ISSUE THREAD

**Issue by 0smile** [ignitionrobotics/ign-gazebo#1039]
Hello, I'm trying to build a crane robot. It works a bit like the SCARA robot, except that it uses ropes to lift objects rather than solid robot arms. Therefore, I need the rope link in ignition to do several things:

1. It can expand and contract without affecting its joint with other links or models
2. Be able to show some flexibility

I'm not sure if they can be achieved, or if one of them can be achieved. I think it is possible to achieve the first point by modifying the geometry and position of link at the same time, but I'm not sure whether this will affect its joint with other objects. Thank you very much if you can answer.

**Comment by chapulina** [comment]
Ignition supports rigid body dynamics, so currently it wouldn't be possible to implement a flexible rope. For your use case, a prismatic joint may be a good approximation, it depends on the scenarios you're trying to test. 

In the past, we've also simulated cables with multiple small cylinders connected together, see for example https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Fire%20hose%20long%20curled.

Finally, in theory, you may be able to integrate a physics engine that supports flexible bodies with Ignition Physics, but at this point, this wouldn't be trivial work.

I hope this answers your question, closing the issue.
