### ISSUE TITLE
Make joint state publisher's topic configurable

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-gazebo#1057]
## Desired behavior

The [JointStatePublisher](https://ignitionrobotics.org/api/gazebo/6.0/classignition_1_1gazebo_1_1systems_1_1JointStatePublisher.html#details) plugin always publishes on the `/world/<world_name>/model/<model_name>/state` topic. It would be convenient to let users change it, especially so that models can be more easily reused across worlds of different names.

## Alternatives considered

N/A

## Implementation suggestion

The topic should be configurable from SDF.

The same way that we accept a `joint_name` element here:

https://github.com/ignitionrobotics/ign-gazebo/blob/59ff8532d0699f18cf9d0e34aa1bc0afecb73671/src/systems/joint_state_publisher/JointStatePublisher.cc#L61

We could accept a `topic` element, like how this other plugin does it for example:

https://github.com/ignitionrobotics/ign-gazebo/blob/59ff8532d0699f18cf9d0e34aa1bc0afecb73671/src/systems/detachable_joint/DetachableJoint.cc#L99-L106

**Comment by jasmeet0915** [comment]
Hi, I was looking for first time issues and have been able to resolve this one. I would like to make a PR for the same!

**Comment by chapulina** [comment]
That's great, thanks @jasmeet0915 !
