### ISSUE TITLE
Visualize center of mass

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-gazebo#110]
Like on Gazebo-classic, it should be possible to visualize links' CoMs so users can debug their models and simulations.

On classic, CoM visuals consist of a sphere scaled proportionally to the link's mass, and lines stretching to the link's bounding box. The sphere represents a uniform ball of lead with the same mass, so if it is as big as your model, your model is as dense as lead!

CoM visualization could be toggled from:

* A world's right-click context menu: toggles all CoMs in the world
* A model's right-click context menu: toggles all CoMs in the model
* A link's right-click context menu

We could also consider adding toggle buttons to an entity's component inspector.

[Here](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/rendering/COMVisual.cc)'s classic's `CoMVisual` implementation as a reference.

And [here](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/1445/page/1)'s the PR where the visuals were added to Gazebo-classic.

Related to #111 and https://github.com/ros-visualization/rviz/issues/1204.

![image](https://user-images.githubusercontent.com/5751272/80619111-13c8a500-89f9-11ea-9fdc-0f43ab447248.png)

**Comment by ahcorde** [comment]
Ign-rendering6 adds this feature https://github.com/ignitionrobotics/ign-rendering/pull/345

next step create a PR on ign-gazebo

FYI @atharva-18

**Comment by chapulina** [comment]
#903
