### ISSUE TITLE
Visualize inertia

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-gazebo#111]
Like on Gazebo-classic, it should be possible to visualize links' inertias so users can debug their models and simulations.

On classic, inertia visuals consist of a 

Inertia visualization could be toggled from:

* A world's right-click context menu: toggles all inertias in the world
* A model's right-click context menu: toggles all inertias in the model
* A link's right-click context menu

We could also consider adding toggle buttons to an entity's component inspector.

[Here](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/rendering/InertiaVisual.cc)'s classic's `InertiaVisual` implementation as a reference. [This world](https://github.com/osrf/gazebo/blob/gazebo11/test/worlds/inertia_rotations.world.erb) has a good test for inertia visuals on various rotations, including non-diagonal terms.

Related to #110 

![image](https://user-images.githubusercontent.com/5751272/80620829-57bca980-89fb-11ea-9958-c83f54fad6d3.png)

**Comment by ahcorde** [comment]
Feature included in fortress https://github.com/ignitionrobotics/ign-gazebo/pull/861
