### ISSUE TITLE
Difficult to move the robot manually on Fortress

### ISSUE THREAD

**Issue by Kakcalu13** [ignitionrobotics/ign-gazebo#1113]
## Environment
* OS Version: Ubuntu 20.04
* Binary build: Fortress 6.0.0 
* Local only (no docker available, or is it?)
* ROS2: Foxy only
* Full SDF file: [freenove_smart_car](https://github.com/feagi/feagi-core/blob/feature-feature-doc-ign-foxy-draft-part3/third_party/gazebo/smart_car/freenove_4wd_car_description/models/sdf/freenove_smart_car.sdf)

## Rendering system info:
 On Linux, provide the outputs of the following commands:
 ```
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 530 [8086:191b] (rev 06)
bwuk@robots:~/feagi-core/src$           echo "$DISPLAY"
:0
bwuk@robots:~/feagi-core/src$           LANG=C glxinfo -B | grep -i '\(direct rendering\|opengl\|profile\)'  # might require installing mesa-utils package
direct rendering: Yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 530 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.0.3
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.3
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
bwuk@robots:~/feagi-core/src$           ps aux | grep Xorg
bwuk         974  0.9  0.7 1047068 61344 tty2    Sl+  Oct11  56:02 /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3
bwuk     3052280  0.0  0.0  18292   664 pts/6    S+   11:44   0:00 grep --color=auto Xorg
```

</details>

## Issue
Since the video is exceed than 10 MB, here is the gif on 3 spots:

![bug1](https://user-images.githubusercontent.com/65916520/137534240-ff549501-10fe-4e36-a0c2-42fe1676ebb2.gif)
![bug2](https://user-images.githubusercontent.com/65916520/137534255-9f871624-9407-469a-a96d-97c31211ff89.gif)
![bug3](https://user-images.githubusercontent.com/65916520/137534472-abfaa222-7bcd-4df6-8df9-92a1932e8a00.gif)

3rd gif is a full video. Due to limit MB, I converted it to gif. 

Citadel doesn't have this one:
https://user-images.githubusercontent.com/65916520/137534771-6077ab6f-53a0-4346-bdda-86712bf2dca5.mp4

**Comment by chapulina** [comment]
I think this may solve it: https://github.com/ignitionrobotics/ign-rendering/pull/446

**Comment by Kakcalu13** [comment]
Nice! I will test it once its updated. I will confirm if it solved the issue. Can't wait!

**Comment by chapulina** [comment]
Hi @Kakcalu13 , are you still having this issue?

**Comment by Kakcalu13** [comment]
Hi there! Sorry for the delay! 

Testing it now, gimme 5 minutes or less

**Comment by Kakcalu13** [comment]
It's no longer an issue! You guys fixed it! Thank you so much!

https://user-images.githubusercontent.com/65916520/144913277-4add9e2b-722f-4933-9fd7-16da5694e832.mp4

P.S.
Just for my own curiosity, do you have any file where you load .obj model to Fortress?
