### ISSUE TITLE
Select Entities plugin selects visual not model

### ISSUE THREAD

**Issue by iche033** [ignitionrobotics/ign-gazebo#1127]
## Environment
* OS Version: Ubuntu Bionic
* Source or binary build?
 source build, 
  * `ign-gui6` branch, commit 443bfac97f6d214bbcc01dc2af7a573e4bba7ea6
  * `ign-gazebo6` branch, commit 3a1adb3152f873348ad5fd4e014e11268e281842
  
## Description
* Expected behavior: clicking on a model in the scene selects the model
* Actual behavior: The visual is selected instead

## Steps to reproduce
1. Launch `diff_drive.sdf` world
2. Left click on one of the vehicles in the 3d scene and see that only individual visuals are selected

I think the fix is just to get the top level visual like it was done in GzScene3d:
https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo5/src/gui/plugins/scene3d/Scene3D.cc#L1633

## Output

Gif shows the current behavior from selecting different parts of the vehicle. 

![mouse_selection](https://user-images.githubusercontent.com/4000684/138148553-b3c84699-eeee-4501-92a9-2d94b995faba.gif)

**Comment by chapulina** [comment]
Fixed in #1150
