### ISSUE TITLE
Tape measure tool

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-gazebo#114]
Users often need to know the distance between points in the simulation. A 3D tape measure tool would help measuring that on the 3D scene as the simulation is running.

[Here](https://github.com/osrf/gazebo/compare/tape_measure)'s an experimental implementation for Gazebo-classic. In that implementation, the tool was attached to objects in simulation and could move with them.

[![Video](https://img.youtube.com/vi/XjszkNSthok/0.jpg)](https://www.youtube.com/watch?v=XjszkNSthok)

**Comment by ahcorde** [comment]
This plugin was added ign-gazebo [here](https://github.com/ignitionrobotics/ign-gazebo/pull/456) and moved to ign-gui [here](https://github.com/ignitionrobotics/ign-gazebo/pull/870) becuase it was a not gazebo specific plugin
