### ISSUE TITLE
SDF String not copied as part of server config copy constructor.

### ISSUE THREAD

**Issue by Mokosha** [ignitionrobotics/ign-gazebo#1182]
In `src/ServerConfig.cc`, the [copy constructor](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo6/src/ServerConfig.cc#L220) for `ServerConfigPrivate` does not copy over the `sdfString` variable. This is surprising, so my recommendation would be one of the following:

(A) If it's a bug, fix it 😃
(B) If it's not a bug, then documentation should be added to that class describing why not.

Thanks!

**Comment by chapulina** [comment]
I believe it's a bug. It's easy to forget to copy variables using that pattern :confused: Would you be able to open a pull request with a fix? Thanks!
