### ISSUE TITLE
Regression in Buoyancy Example, neutral vehicle slowly sinks

### ISSUE THREAD

**Issue by arjo129** [ignitionrobotics/ign-gazebo#1210]
## Environment
* OS Version: Ubuntu 20.04
* Source or binary build?
  Source 97f2e9c8499fdeb89d45220a89b7d570c9ce6690

## Description

* Expected behavior: The center vehicle in the neutral Buoyancy example in the `buoyancy.sdf` example is supposed to remain stationary.
* Actual behavior: Instead it is sinking.

![sinking_buoyant_object](https://user-images.githubusercontent.com/542272/141979483-30f48f49-b7d2-419a-a95a-43ed923cc740.gif)

## Steps to reproduce

1. `ign gazebo buoyancy.sdf`

## More details

It seems like the cause is the way the buoyancy plugin is structured. In #1064 a change was made to prevent newly spawned objects from developing a spin. To do this, we skip one iteration of the update if the pose is not ready. Unfortunately this leads to problems as it gives an initial velocity to objects. Without damping this leads to the slow sinking we see above.

**Comment by chapulina** [comment]
Let's keep it open until graded buoyancy is fixed too
