### ISSUE TITLE
Control lights

### ISSUE THREAD

**Issue by iche033** [ignitionrobotics/ign-gazebo#122]
Add the ability to turn lights on/off programmatically and configure their properties, e.g. color, attenuation.. Also, add ign-transport topics so that we can expose topics for light control.

**Comment by chapulina** [comment]
It would also be great to make the component inspector call those new topics to edit lights from the GUI.

Also, the commands should probably be handled by the `UserCommands` system, so we can eventually support undo for it.

**Comment by ahcorde** [comment]
PR https://github.com/ignitionrobotics/ign-gazebo/pull/482
