### ISSUE TITLE
Insert models from local paths

### ISSUE THREAD

**Issue by iche033** [ignitionrobotics/ign-gazebo#123]
Currently models are downloaded from fuel (app.ignitionrobotics.org) and saved to fuel cache in `~/.ignition/fuel`.  The idea is to support pulling models locally without going through fuel.

Related design doc:
https://github.com/ignitionrobotics/design/pull/1

Related PRs:
https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-fuel-tools/pull-requests/123/page/1
https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/532/page/1

**Comment by nkoenig** [comment]
@JShep1 , we need this for SubT. Are you able to pick this up and target and MVP to blueprint?

**Comment by JShep1** [comment]
@nkoenig Sure, I'll prioritize this issue and try to get started later today/tomorrow.

**Comment by nkoenig** [comment]
Awesome, thanks!

**Comment by chapulina** [comment]
Just clarified with @nkoenig and @JShep1 that I'll take this one and John will work on #31.

**Comment by peci1** [comment]
Hasn't this been resolved? I can launch the SubT simulator pulling local models when I pass `localModel:=true`.

**Comment by iche033** [comment]
I think for subt, if you don't have the model in fuel cache, the materials will still fail to load with `localModel:=true`. Related issue #286

**Comment by chapulina** [comment]
I believe this has been solved and is available on:

* Blueprint since 2.24.0
* Citadel since 3.3.0
* Dome since 4.0.0~pre1
