### ISSUE TITLE
Triggered publisher tests are disabled on ign-gazebo7 (main)

### ISSUE THREAD

**Issue by scpeters** [ignitionrobotics/ign-gazebo#1267]
Re-enable these when the underlying issue is fixed

* https://github.com/ignitionrobotics/ign-gazebo/pull/1264/files#diff-b2450a2967140ea45ab266ec7e723d17fe032a2fd14019a34cbcf0d2b2a734b9
* https://github.com/ignitionrobotics/ign-gazebo/pull/1264#issuecomment-1003142524

**Comment by chapulina** [comment]
Re-enabled in https://github.com/ignitionrobotics/ign-gazebo/pull/1271
