### ISSUE TITLE
Invalid package dependencies in ign_gazebo5

### ISSUE THREAD

**Issue by harshmahesheka** [ignitionrobotics/ign-gazebo#1278]
I was trying to build ign_gazebo based on steps on https://github.com/ignitionrobotics/ign-gazebo/tree/ign-gazebo5#readme, but in the dependencies, it contains ignition-physics6 which is not available on the ign_physics site. You can check those dependencies on https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo5/CMakeLists.txt  .

**Comment by chapulina** [comment]
Ahh I think the problem is this line:

`git clone https://github.com/ignitionrobotics/ign-gazebo -b main`

It should be 

`git clone https://github.com/ignitionrobotics/ign-gazebo -b ign-gazebo5`

Can you give that a try?

**Comment by harshmahesheka** [comment]
Oh, yes it worked. Thanks for the help .Also 
`sudo apt-add-repository ppa:dartsim/ppa `
`sudo apt-get update`
this must be done before 
`sudo apt -y install   $(sort -u $(find . -iname 'packages-'$SYSTEM_VERSION'.apt' -o -iname 'packages.apt') | tr '\n' ' ')
`
Should I add a Pull request?

**Comment by harshmahesheka** [comment]
Yeah, it worked. Thanks for the help. Also, I want to work on this issue could you please assign it to me.

**Comment by chapulina** [comment]
Thanks for the fix!
