### ISSUE TITLE
ign-gazebo regressions test failing INTEGRATION_rgbd_camera.test_ran

### ISSUE THREAD

**Issue by tfoote** [ignitionrobotics/ign-gazebo#131]
On linux: https://build.osrfoundation.org/job/ignition_gazebo-ci-master-bionic-amd64/
And MacOS: https://build.osrfoundation.org/job/ignition_gazebo-ci-master-homebrew-amd64/

Test `INTEGRATION_rgbd_camera.test_ran` is failing. 

`Expected: (depthBuffer) != (nullptr), actual: NULL vs 8-byte object <00-00 00-00 00-00 00-00>`

From: https://build.osrfoundation.org/job/ignition_gazebo-ci-master-bionic-amd64/lastCompletedBuild/consoleText

<details>

```
109: /var/lib/jenkins/workspace/ignition_gazebo-ci-master-bionic-amd64/ign-gazebo/test/integration/rgbd_camera.cc:95: Failure
109: Expected: (depthBuffer) != (nullptr), actual: NULL vs 8-byte object <00-00 00-00 00-00 00-00>
109/116 Test #109: INTEGRATION_rgbd_camera ..............................***Exception: SegFault  1.90 sec
```
</details>

**Comment by chapulina** [comment]
I think this was fixed for `ign-gazebo2` on [this PR](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/570/page/1), which is being forward-ported to `ign-gazebo3` on #136

**Comment by j-rivero** [comment]
The job pointed by Tully checks the `master` branch of `ign-gazebo` and the PR landed in `ignition-gazebo3` branch which does not seems to suffer from the problem before/after merging the PR https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo3-bionic-amd64/ . Should we prepare a forward to master branch?

**Comment by chapulina** [comment]
> Should we prepare a forward to master branch?

This is happening on #144 :wink:

**Comment by j-rivero** [comment]
> This is happening on #144 wink

confirmed, I don't see the problem in the CI of that PR.
