### ISSUE TITLE
Reset model's position feature

### ISSUE THREAD

**Issue by Kakcalu13** [ignitionrobotics/ign-gazebo#1328]
Is it possible to add the shortcut to reset the robot's position include all components such as joint, cmd_vel? 

Like the old gazebo where you can just press ctrl+shift+ R (I think) to reset the model's position. Can we have it on Citadel or Fortress?

**Comment by mjcarroll** [comment]
There is ongoing work to reset the state of the entire simulation world here: https://github.com/ignitionrobotics/ign-gazebo/issues/1107

This currently can't be applied on a per model basis, but perhaps could be extended to in the future.
