### ISSUE TITLE
What's the different content about the ‘distributed’  features between classic gazebo and ignition gazebo ?

### ISSUE THREAD

**Issue by xuqiaobo** [ignitionrobotics/ign-gazebo#1423]
I have read the classic gazebo architecture page(https://gazebosim.org/tutorials?tut=architecture&cat=get_started#System)  and ignition gazebo architecture page(https://ignitionrobotics.org/docs/all/architecture) , the **Two Pages** I found the world  **distributed**, for the two different simulators, what is the difference ? and what is meaning of the "distributed"?

Hope your answer

**Comment by WarrenSkywalker** [comment]
yep, I am also confused with the word "distributed", is there any example showing how ign gazebo loads large scale model distributedly?
