### ISSUE TITLE
How to statistic collision messages in the simulation process using ignition gazebo?

### ISSUE THREAD

**Issue by xuqiaobo** [ignitionrobotics/ign-gazebo#1424]
At previous, I used classic gazebo, get a gazebo topic ：/gazebo/default/physics/contacts， and the message like follows:
![image](https://user-images.githubusercontent.com/29470717/161377420-d66b5f68-d41d-41dc-b913-0fca35d5153f.png)

but in ignition gazebo, I didn't find topic like this, Did you have any experience to achieve the result in ignition gazebo like in the classic gazebo

**Comment by chapulina** [comment]
Hi @xuqiaobo , please direct questions to https://answers.gazebosim.org/. This issue tracker is for bug reports and feature requests.

And also please use the issue template next time.

See you at Gazebo Answers.
