### ISSUE TITLE
[Bug]: Camera image does not show the actual color of the mesh

### ISSUE THREAD

**Issue by hardesh** [ignitionrobotics/ign-gazebo#1435]
## Environment
* OS Version: Ubuntu 20.04
* Source or binary build? Ignition Fortress Binary with ROS2 Rolling
* If this is a GUI or sensor rendering bug, describe your GPU and rendering system. Otherwise delete this section: Mostly bug in sensor plugin 
    
## Description

* Actual behavior: 
I generated the `.dae` using blender today and applied a color on the box. That color is visible in the actual ignition GUI but it's not visible in the camera image.
![Screenshot from 2022-04-11 14-32-57](https://user-images.githubusercontent.com/37694296/162703964-59539bfd-f280-4f5c-a021-bdacb299e823.png)

* Expected behavior:
Actual color of the mesh should be visible in the camera image

**Comment by mjcarroll** [comment]
When you applied the material, how did you do it? 

Can you upload the model and sdf somewhere so that it can be reproduced?

**Comment by hardesh** [comment]
Hi @mjcarroll,

I applied the material using UV unwrap in Blender. 

Here's the model
[apriltag_block.zip](https://github.com/ignitionrobotics/ign-gazebo/files/8466348/apriltag_block.zip)

**Comment by hardesh** [comment]
Hey @mjcarroll,
is there any update on this? curious to know the details

also, can you point me towards a design doc if it exists? want to know more about the workings of the simulator

**Comment by mjcarroll** [comment]
> is there any update on this? curious to know the details

On my list to take a look at this morning.

> also, can you point me towards a design doc if it exists? 

Probably the best jumping-off point is here: https://ignitionrobotics.org/docs/all/architecture

**Comment by mjcarroll** [comment]
I'm having trouble reproducing, this is what it looks like with `fortress` binaries on my system: 
![image](https://user-images.githubusercontent.com/279701/163275780-5d940d63-28dc-4edd-8e2c-ef4dfefb0dfe.png)
![image](https://user-images.githubusercontent.com/279701/163275815-2d7a9f09-78e0-46ed-94e4-e0d02b322ae9.png)

The camera parameters are:

```
            <sensor name="camera" type="camera">
                <always_on>1</always_on>
                <update_rate>20</update_rate>
                <camera name="camera">
                    <horizontal_fov>1.0472</horizontal_fov>
                    <lens>
                        <intrinsics>
                            <!-- fx = fy = width / ( 2 * tan (hfov / 2 ) ) -->
                            <fx>1108.5</fx>
                            <fy>1108.5</fy>
                            <!-- cx = ( width + 1 ) / 2 -->
                            <cx>640.5</cx>
                            <!-- cy = ( height + 1 ) / 2 -->
                            <cy>480.5</cy>
                            <s>0</s>
                        </intrinsics>
                    </lens>
                    <image>
                        <width>1280</width>
                        <height>960</height>
                        <format>R8G8B8</format>
                    </image>
                    <clip>
                        <near>0.01</near>
                        <far>300</far>
                    </clip>
                    <noise>
                        <type>gaussian</type>
                        <mean>0</mean>
                        <stddev>0.007</stddev>
                    </noise>
                </camera>
            </sensor>
```

**Comment by hardesh** [comment]
I'm using the sensor like this. Am I missing something?
```
<sensor name="color" type="camera">
        <pose>0 0 0 0 0 0</pose>
        <update_rate>6</update_rate>
        <always_on>0</always_on>
        <camera>
          <horizontal_fov>1.22</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
          </image>
          <clip>
            <near>0.1</near>
            <far>50</far>
          </clip>
          <lens>
            <intrinsics>
              <fx>615.9603271484375</fx>
              <fy>616.227294921875</fy>
              <cx>419.83026123046875</cx>
              <cy>245.1431427001953</cy>
              <s>0</s>
            </intrinsics>
          </lens>
        </camera>
      </sensor>
```

**Comment by mjcarroll** [comment]
The only difference I'm seeing is: `<format>R8G8B8</format>`, but given that you are seeing other color, that seems unlikely to be it.

How are you loading the model, is it possible that the GUI/server side is using a cached version?

**Comment by iche033** [comment]
can you check the first of ignition-rendering6 you have?

One thing to try is updating to the latest version, which is currently 6.3.1. Also make sure that it's running with the ogre2 render  engine. There is also an `~/.ignition/rendering/ogre2.log` to indicate if there're any issues (look for ogre exceptions)

**Comment by Kakcalu13** [comment]
Hi,

I saw this and figured I could help. 

So, I tested it on my sdf. See the result
![image](https://user-images.githubusercontent.com/65916520/164740508-4bf8abff-d42a-4f62-8ce8-8ec638e505e5.png)

What is your version on Fortress? You can check by `ign gazebo --version`


I looked into your camera paramter. I think it's because you are calling `camera` instead of `rgb_camera`.

See here from my code:
```
      <sensor name="rgbd_camera" type="rgbd_camera">
          <update_rate>100</update_rate>
          <visualize>true</visualize>
          <always_on>1</always_on>
          <topic>IR0</topic>
          <camera>
            <horizontal_fov>1.2</horizontal_fov>
            <image>
              <width>1</width>
              <height>1</height>
              <format>L_INT8</format>
            </image>
            <clip>
              <near>0.02</near>
              <far>10.0</far>
            </clip>
          </camera>
      </sensor>
```

Obviously, you will need to adjust this to your own setting, but this is official sample from ign's rgb camera. 

Can you let us know if it's fixed on your end? I humbly encourage you to discuss more about this in gazebo community since this is related to code isssues, not ign bug.

**Comment by hardesh** [comment]
Hi @Kakcalu13,
Thanks for letting me know. I haven't had a chance to take a look at this :sweat_smile: . It's on my TODO list. I'll try again on Monday

**Comment by hardesh** [comment]
Just installed ign on _fresh_ ubuntu 22! `ign gazebo --version` is giving me 
```
Ignition Gazebo, version 6.9.0
Copyright (C) 2018 Open Source Robotics Foundation.
Released under the Apache 2.0 License.
```

Still facing the same issue

**Comment by hardesh** [comment]
Hi @iche033,
Checked the log. Found some relevant lines related to the model:
```
Added resource location '/home/harshal/sim_ws/install/movus_ignition_sim/share/movus_ignition_sim/models/apriltag_block/meshes' of type 'FileSystem' to resource group 'General' with recursive option
23:12:27: Initialising resource group General
23:12:27: Added resource location '/home/harshal/sim_ws/install/movus_ignition_sim/share/movus_ignition_sim/models/apriltag_block/meshes/' of type 'FileSystem' to resource group 'General'
23:12:27: Texture memory budget exceeded. Stalling GPU.
23:12:27: Stalling was not enough. Freeing memory.
23:12:27: Can't assign material scene::Material(65429) because this Material does not exist. Have you forgotten to define it in a .material script?
23:12:27: Can't assign material scene::Material(65428) because this Material does not exist. Have you forgotten to define it in a .material script?
23:12:27: Vertex Shader: 100000000VertexShader_vs
Fragment Shader: 100000000PixelShader_ps
 GLSL validation result : 
active samplers with a different type refer to the same texture image unit
23:12:27: Vertex Shader: 100000001VertexShader_vs
Fragment Shader: 100000001PixelShader_ps
 GLSL validation result : 
active samplers with a different type refer to the same texture image unit
```

I'm can't understand what exactly is happening though

**Comment by Kakcalu13** [comment]
> Just installed ign on _fresh_ ubuntu 22! `ign gazebo --version` is giving me
> 
> ```
> Ignition Gazebo, version 6.9.0
> Copyright (C) 2018 Open Source Robotics Foundation.
> Released under the Apache 2.0 License.
> ```
> 
> Still facing the same issue

I wonder if it is because of ubuntu 22. :thinking: 

Let me know if the code I gave you changed anything

**Comment by hardesh** [comment]
> I wonder if it is because of ubuntu 22. thinking

I was facing the same issue on Ubuntu 20

Also, your snippet did not work

**Comment by hardesh** [comment]
Hi everyone,

I just checked the world file today and found out that I was using OGRE1 engine. Extremely sorry for wasting everyone's time. Closing this issue.

Is there any doc where I can read about the difference between OGRE1 and OGRE2?

**Comment by Kakcalu13** [comment]
Here is the [doc](https://gazebosim.org/api/rendering/3.2/renderingplugin.html)

Here is example on [ogre and ogre2](https://github.com/ignitionrobotics/ign-rendering/tree/ign-rendering6/tutorials)

Speak of ogre1/ogre2...I wonder if it is possible to run ogre1 while camera and everything else on ogre2 or highest quality. :thinking:  I think this is great way to experiment!

**Comment by hardesh** [comment]
Thanks for sharing!
