### ISSUE TITLE
Ability to deform or manipulate meshes once imported?

### ISSUE THREAD

**Issue by edwardwterry** [ignitionrobotics/ign-gazebo#1460]
In my application I am populating my environment with meshes, each of which has a default set of dimensions. Based on perception updates, I will be improving my knowledge of their shape parameters and would therefore like to be able to update the meshes to reflect these measurements. I wonder if there is any way to handle this within Gazebo, short of updating the mesh in a separate process, then reimporting it. Thanks!

**Comment by chapulina** [comment]
Please direct questions to https://answers.gazebosim.org/. This issue tracker is for bug reports and feature requests.

And also please use the issue template next time.

See you at Gazebo Answers.
