### ISSUE TITLE
Add buoyancy plugin

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-gazebo#159]
@nkoenig started a port that was almost merged on BitBucket, but didn't get in in time for the GitHub migration. We should reopen that PR soon so it's not left behind.

https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/506/page/1

**Comment by nkoenig** [comment]
Ported in pull request #252
