### ISSUE TITLE
List GUI plugins in alphabetical order

### ISSUE THREAD

**Issue by nkoenig** [ignitionrobotics/ign-gazebo#175]
The GUI menu that lists available plugins is not in alphabetical order.
![alpha](https://user-images.githubusercontent.com/1587438/83694785-a4247780-a5ad-11ea-834e-5f067c34b9ba.png)

**Comment by chapulina** [comment]
The fix would go on `ign-gui`, here's where the menu gets populated: https://github.com/ignitionrobotics/ign-gui/blob/a60cb7d61339b407ff3285ddbf16f618c4c4b3b9/src/MainWindow.cc#L95

**Comment by chapulina** [comment]
Solved for Dome in https://github.com/ignitionrobotics/ign-gui/pull/71

I'll backport to Blueprint / Citadel.

**Comment by chapulina** [comment]
* This regressed when the filter was added in https://github.com/ignitionrobotics/ign-gui/pull/277. Reopening
