### ISSUE TITLE
Github Actions CI tests are failing because system shared libraries cannot be found

### ISSUE THREAD

**Issue by azeey** [ignitionrobotics/ign-gazebo#184]
A lot of the integration tests are failing because the shared libraries for systems are not found. Looking at this line https://github.com/ignition-tooling/ubuntu-bionic-ci-action/blob/fea60bd43886762974f4d40d63a469c2714bb1be/entrypoint.sh#L72, I think we might need to add a `make install` before running tests.

**Comment by chapulina** [comment]
I believe this is already fixed:

https://github.com/ignitionrobotics/ign-gazebo/blob/fac36a4b06c3ba45b14c72163f9b390721edbda6/.github/ci/after_make.sh#L6-L7
