### ISSUE TITLE
Create joints from the GUI

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-gazebo#188]
Gazebo-classic has an interface to create joints in edit mode. See the [Model Editor tutorial](http://gazebosim.org/tutorials?tut=model_editor#CreateJoints). We should port this to Ignition.

![image](https://user-images.githubusercontent.com/5751272/83929098-15e3f900-a747-11ea-83b4-6e6b079b6df8.png)

Key features:

* Pick child and parent links either from a dropdown or clicking on the 3D scene
* Configure all joint properties on the dialog (on Ignition this could be done in the component inspector)
* Joint is visualized as a line and an axis (requires #106 )

**Comment by peci1** [comment]
I think this has already been done in the recent Model Editor PR.

**Comment by chapulina** [comment]
True, I'm closing this, but we still should address #1232 to wrap up the model editor work.

**Comment by mkschreder** [comment]
Is this supposed to be available in gz-garden?
