### ISSUE TITLE
Visualize lights

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-gazebo#193]
Port Gazebo-classic's light visualization to Ignition. These are good for debugging and necessary to enable manipulation of lights in the 3D scene.

Some improvements we could do on top of the previous implementation:

* Make light visuals selectable on 3D: https://github.com/osrf/gazebo/issues/1438
* Make it possible to hide light visuals: https://github.com/osrf/gazebo/issues/2327

---

## Point light

![pointlight](https://user-images.githubusercontent.com/5751272/83931101-b9390c00-a74f-11ea-865b-4e3bbb3e4688.png)

## Spot light

![spotlight](https://user-images.githubusercontent.com/5751272/83931115-d1109000-a74f-11ea-8306-0227a76179f8.png)

## Directional light

![directional](https://user-images.githubusercontent.com/5751272/83931129-e5ed2380-a74f-11ea-8b28-3168d24fbdd9.png)

**Comment by ahcorde** [comment]
This is already merged https://github.com/ignitionrobotics/ign-rendering/pull/202. It's available from Edifice
