### ISSUE TITLE
Graphical interface full screen not working

### ISSUE THREAD

**Issue by mohamedsayed18** [ignitionrobotics/ign-gazebo#224]
`<gui fullscreen="0">`. The world always launch without fullscreen whether the value is `0` or `1`

**Comment by chapulina** [comment]
Thank you for ticketing the issue! Just a clarification:

> The world always launch with fullscreen whether the value is 0 or 1

The current behaviour is that the world is launched _without_ a full screen. If it were a full screen, Ignition Gazebo's UI would take up the entire monitor.

**Comment by chapulina** [comment]
Addressed on #254.
