### ISSUE TITLE
Choose rendering engine from command line

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-gazebo#227]
This requires https://github.com/ignitionrobotics/ign-rendering/issues/100

We already have the ability to choose the physics engine from the command line with the `--physics-engine` option (see [full tutorial](https://github.com/ignitionrobotics/ign-gazebo/blob/master/tutorials/physics.md)).

The same way, we also need to choose the rendering engine. One thing to note though is that we may want the ability to choose the rendering engine for the server and client separately. So here's a suggestion:

```
--rendering-engine : sets for client and server
--rendering-engine-client : sets for client only
--rendering-engine-server : sets for the server (there may be multiple systems making use of this)
```

**Comment by JShep1** [comment]
Closing as this functionality is now supported with the previously linked pull request
