### ISSUE TITLE
Actor tutorial

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-gazebo#228]
We have Actor support from Citadel, but there's not much documented. Here's the [equivalent tutorial for Gazebo-classic](http://gazebosim.org/tutorials?tut=actor&cat=build_robot).

Some things that need to be covered:

* How to add and configure an actor through SDF 
* How to spawn an actor through the create service
* How to control an actor from a plugin

Slightly connected to #91.

**Comment by maryaB-osr** [comment]
@mohamedsayed18 is looking into this

**Comment by chapulina** [comment]
See this PR: https://github.com/ignitionrobotics/docs/pull/43
