### ISSUE TITLE
3D plot plugin

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-gazebo#231]
Gazebo-classic's [LinkPlot3DPlugin](https://github.com/osrf/gazebo/blob/gazebo11/plugins/LinkPlot3DPlugin.hh) traces the trajectory of a link in the rendering scene by publishing 3D markers.

Try `gazebo worlds/plot3d.world `:

![plot3d](https://user-images.githubusercontent.com/5751272/86315695-b0691800-bbdf-11ea-937b-d0a223be68b7.gif)

It would be nice to port it to Ignition. We already have markers, so it should be a matter of implementing a system plugin that publishes markers according to the current link poses.

**Comment by luccosta** [comment]
Hi @chapulina, I'm interested on this Issue. I'm planning to create a file with for the plugin as in Gazebo-classic. Should I put this on `/src`? And what branch to target?

> We already have markers

Planning to use [marker example](https://github.com/ignitionrobotics/ign-gazebo/blob/master/examples/standalone/marker/marker.cc) as guide.

**Comment by chapulina** [comment]
Thanks, @luccosta !

You can create a new directory under [src/systems](https://github.com/ignitionrobotics/ign-gazebo/tree/master/src/systems) for your new system. I think you'll probably use some `Each` calls on a `PostUpdate` callback to get link poses and publish the marker messages.

The markers are available since `ign-gazebo3`, which is Ignition Citadel, so it would be great if you targeted that branch and after merging we'll forward-port it to `master`.

**Comment by chapulina** [comment]
Done in #917
