### ISSUE TITLE
Support heightmaps

### ISSUE THREAD

**Issue by caguero** [ignitionrobotics/ign-gazebo#237]
We should add support for creating terrain based on heightmaps. This is also relevant for supporting DEMs. See issue #235.

**Comment by chapulina** [comment]
I'll be looking into supporting heightmaps on `ign-rendering` with Ogre 1 and @scpeters will look into enabling it on `ign-physics` using DART.

**Comment by chapulina** [comment]
* SDFormat PR: https://github.com/osrf/sdformat/pull/388
* Ignition Rendering PR: https://github.com/ignitionrobotics/ign-rendering/pull/180

**Comment by chapulina** [comment]
Ignition Gazebo PR: https://github.com/ignitionrobotics/ign-gazebo/pull/487
