### ISSUE TITLE
Apple support for ign command line tool

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gazebo#25]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/25)) by Nate Koenig (Bitbucket: [Nathan Koenig](https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/)).**

----------------------------------------
# Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Q&A board for common solutions: http://answers.gazebosim.org
    * Checked that your issue isn't already filed.
    * Checked that there is not already an Ignition package that provides the described functionality: https://ignitionrobotics.org/libs

# Description 

The `UNIT_ign_TEST` fails on Apple, through homebrew, when using the `ign gazebo` command line tool. In general, the `ign gazebo` command line tool fails to load the `libignition-gazebo2-ign.dylib`. Other packages, such as `ign-transport` and `ign-msgs` work fine. There might be a problem associated with loading a component library.

# Steps to Reproduce

1. Change the `src/ign_TEST.cc` to use `ign gazebo` instead of `ign-gazebo`.
2. Install gazebo on homebrew
3. Run the `/bin/UNIT_ign_TEST` test.

**Expected behavior:**  

The test should pass.

**Actual behavior:**

The test fails

**Reproduces how often:** 

All the time.

# Versions

Gazebo 2+

# Additional Information

* [Pull request #296](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/296)
* [Pull request #336](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/336)

**Comment by scpeters** [comment]
I have been successful with `ign gazebo -s` when invoked with the homebrew version of ruby and have added this as a test command to the `ignition-gazebo*` formulae in https://github.com/osrf/homebrew-simulation/pull/1221

**Comment by scpeters** [comment]
I am debugging the `UNIT_ign_TEST` on macOS to see if we can enable at least part of it

**Comment by scpeters** [comment]
I've enabled `UNIT_ign_TEST` on macOS in https://github.com/ignitionrobotics/ign-gazebo/pull/477 by making use of the homebrew ruby formula. It also should provide more helpful error messages if a library fails to load

**Comment by chapulina** [comment]
Closed by #477
