### ISSUE TITLE
Touch plugin enabled

### ISSUE THREAD

**Issue by mohamedsayed18** [ignitionrobotics/ign-gazebo#273]
The `<enable>` tag is not enabled. I tried to set it to `false` but it always enabled.
https://github.com/ignitionrobotics/ign-gazebo/blob/deaa059e7a82e177279343de125c39b44f09237a/src/systems/touch_plugin/TouchPlugin.cc#L187-L192

This condition is always achieved.
I think the problem is with `Get<bool>`

**Comment by azeey** [comment]
Oof, yeah that should be `_sdf->Get<bool>("enabled", false).first`. Mind creating a PR?

**Comment by mohamedsayed18** [comment]
I tried to edit the `workspace/src/sdformat/include/sdf/Element.hh` but it didn't work. Is this the write file?

**Comment by azeey** [comment]
I meant line 188 https://github.com/ignitionrobotics/ign-gazebo/blob/deaa059e7a82e177279343de125c39b44f09237a/src/systems/touch_plugin/TouchPlugin.cc#L188. `second` should be `first`.

`Get` returns a `std::pair` where the first value is the actual value of the sdf parameter and the second value indicates whether the parameter was set.
