### ISSUE TITLE
Add service for rendering multiple markers

### ISSUE THREAD

**Issue by mcres** [ignitionrobotics/ign-gazebo#287]
Currently, Ignition Gazebo doesn't have a service that supports rendering multiple markers at once.
While working on #229, we've seen that if several markers are needed at a specific moment, requesting them individually could drop the performance significantly due to transport messages costs.

This could be done using the already existing [Marker_V message](https://github.com/ignitionrobotics/ign-msgs/blob/master/proto/ignition/msgs/marker_v.proto) as the request and most of the existing code in `MarkerManager.cc`, resulting in a [service callback](https://github.com/ignitionrobotics/ign-gazebo/blob/master/src/rendering/MarkerManager.cc#L593-L597) very similar to the `/marker` service, which renders an individual marker.
It would probably be nice to also add an example of the new functionality [here](https://github.com/ignitionrobotics/ign-gazebo/blob/master/examples/standalone/marker/marker.cc).

**Comment by JShep1** [comment]
Thanks for suggesting this, I created a PR [here](https://github.com/ignitionrobotics/ign-gazebo/pull/302/files) adding this functionality.

**Comment by mcres** [comment]
Awesome, thanks for the PR!

**Comment by chapulina** [comment]
#302
