### ISSUE TITLE
Insert model from the GUI

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gazebo#31]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/31)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------

It is convenient for users to construct environments through the UI. To be able to do that, they need to be able to insert new models into simulation. This issue is about creating a GUI plugin which allows users to inspect and insert SDF models from:

* custom local paths (Requires #123)
* Fuel's local cache
* Fuel's online models

A few more nice features:

* Display resource names and thumbnails
* Display resources organized by folders
* Search bar to filter folders and resources
* A button to add new local folders to be listed
* Drag resources from one local folder to another to copy / move them
* Drag resources into a Fuel user to upload to that user's account

# Alternatives

* Since Blueprint, users are already able to drag models directly from Fuel on the browser. That doesn't cover local models though.
* It's common on various programs for the user to drag SDF files from a file browser. We should also support that use case besides the plugin in question.

# Additional resources

* Feature request: https://github.com/osrf/subt/issues/130
* [Create entity service](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/143/a-6-user-command-spawn-factory-create/diff)
* Gazebo-classic's [InsertModelWidget](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/gui/InsertModelWidget.hh)
    * Lists model by their name in `model.config`
    * Lists all local paths in `GAZEBO_MODEL_PATH`
    * Lists all models in https://models.gazebosim.org
    * Has partial support for Fuel
    * Interaction:
        1. Click on model name
        1. A temp preview visual is attached to mouse, at Z = 0 height
        1. Click on 3D scene, model is spawned
    ![classic_insert](https://user-images.githubusercontent.com/5751272/82961035-0a3b4a00-9f71-11ea-89db-275194edac38.png)
* GzWeb's [insert menu](https://github.com/osrf/gzweb/blob/9598775be65535fc50555b469d712620e7193129/gz3d/client/index.html#L53)
    * Lists a hardcoded list of models organized by categories
    * Lists models by their name and thumbnail
    * Same interaction as Gazebo-classic
    ![gzweb_insert](https://user-images.githubusercontent.com/5751272/82966273-61481b80-9f7f-11ea-8a68-304cd2cf9af0.png)

**Comment by chapulina** [comment]
@JShep1, here's a quick idea I sketched just so we have a high-level notion of what we're going for. @ColeOSRF is working on a proper mockup.

The first version of this plugin should focus on inserting models from local paths. Fuel can come on follow up PRs. Other features like filtering can also come later, but it would be nice to organize the data in a way that will allow us to do this easily in the future, using [QSortFilterProxyModel](https://doc.qt.io/qt-5/qsortfilterproxymodel.html) for example.

![20200527_154217](https://user-images.githubusercontent.com/5751272/83081948-c6127d00-a036-11ea-9ed8-2e36e5f7eff9.jpg)

**Comment by ColeOSRF** [comment]
Here is a very early mockup of the content browser based on Louise's sketch. 

![ContentBrowser](https://user-images.githubusercontent.com/42189537/83461607-064e7280-a41e-11ea-94b0-561de8de792e.png)

**Comment by chapulina** [comment]
Thanks, that's neat, @ColeOSRF! Some comments:

* I see each resource has a name and username. But I think that the usernames are not necessary, because local resources won't have usernames, and I assume that if you choose a Fuel user all assets will be tied to that user.
* I see what you were going for with the folder structure under **Local**, something similar to how game engines let a user bundle all resources related to a project in a single place.
    Our use case is slightly different though. It's common for projects like SubT to install their own assets somewhere on disk. Ignition will know about all the paths from various projects at the same time so the user can insert any of them into simulation. In that situation, we end up with a list of various unrelated paths that are one-level deep.
    See Gazebo-classic's menu for example.  Since here we're listing the resources on the right-side, the list of paths may not even be collapsible. And the lists are usually ugly long paths that we may want to truncate. In that case, it's also helpful to let the users add new paths to the list - that's what the **Add Path** button below does, and that's what I was going for with the :heavy_plus_sign: on my sketch above.
    Let me know what you think and if you have any ideas around the usability of these paths.

    ![model_paths](https://user-images.githubusercontent.com/5751272/83463937-47e21c00-a424-11ea-8d25-4d335926b3db.png)

**Comment by JShep1** [comment]
This looks great, I've been working on the logic.  @ColeOSRF Do you think you could provide a No Thumbnail Available image?  Also, I'll likely have more questions as I get to the GUI side of things so I might reach out then.

**Comment by chapulina** [comment]
@JShep1 , #172 adds a transport interface that you can use to query and update local resource paths.

**Comment by JShep1** [comment]
> @JShep1 , #172 adds a transport interface that you can use to query and update local resource paths.

Awesome!  I got all the local model location and generation logic in, messing with the QML now

**Comment by ColeOSRF** [comment]
Here is a revised UI. I redid the local paths section so hopefully it's more representative of our needs. I have two UI examples. One lists the folder contents as a list and the other as thumbnails with the two buttons to switch between list/thumbnail view in the upper right of the area that contains the assets. Unlike Gazebo-classic I do not have a list of the assets under the folder on the left. I figured it was repetitive and makes it harder to navigate the folder structures. 

There are still some missing things like scroll bars and it's very unrefined. Font is bad and that sort of thing but hopefully it's a little closer now. 

![ContentBrowser_01](https://user-images.githubusercontent.com/42189537/83818493-5aef2900-a67c-11ea-96e7-1e35aa2177d4.png)
![ContentBrowser_02](https://user-images.githubusercontent.com/42189537/83818495-5d518300-a67c-11ea-9646-f72016f4cca0.png)

**Comment by chapulina** [comment]
> Unlike Gazebo-classic I do not have a list of the assets under the folder on the left.

That's perfect!

This is looking great to me, Cole! No more comments from me.

**Comment by chapulina** [comment]
Done on #173 and #263
