### ISSUE TITLE
Grid3D crashes

### ISSUE THREAD

**Issue by nkoenig** [ignitionrobotics/ign-gazebo#312]
1. `ign gazebo -v 4`
2. Insert the `Grid 3D` plugin.
3. The screen changes to this:

![grid3d](https://user-images.githubusercontent.com/1587438/91225681-de973f80-e6d8-11ea-90b7-a689c216fec0.png)

4. Clicking on the window causes it to crash

Also, what is the difference between `Grid Config` and `Grid 3d`?

**Comment by claireyywang** [comment]
I think grid 3d is the outdated grid plugin that is supposed to be replaced by grid config. `grid_3d` is `ign-gui` plugin. `grid_config` is `ign-gazebo` plugin. I remember @chapulina and I talked about this a while ago. Maybe we can remove `grid_3d` to avoid confusion?

**Comment by chapulina** [comment]
Yeah `ign-gui`'s `Grid3D` works with `ign-gui`'s `Scene3D`. I think we should move `ign-gazebo`'s `GridConfig` to `ign-gui` and make it work with both `ign-gui`'s scene and `ign-gazebo`'s scene.

**Comment by chapulina** [comment]
This should be fixed by #598

**Comment by chapulina** [comment]
I think https://github.com/ignitionrobotics/ign-gui/pull/324 completely closes this.
