### ISSUE TITLE
Widget to choose / reset camera angles

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gazebo#33]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/33)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
# Summary

Have a widget that allows moving the camera to canonical angles, focused on given robots, as well as resetting to the initial view.

# Motivation

When navigating a 3D environment, it's helpful to be able to switch the camera view to canonical angles, as well as resetting to the initial world view.

# Describe alternatives you've considered

Gazebo-classic has a widget with all 6 canonical angles, zoom, and a reset view button. The view focused on the currently selected model.

We could implement this in different ways, like right-clicking the model, having keyboard shortcuts, etc.

# Additional context

* [Feature request](https://bitbucket.org/osrf/subt/issues/130/some-suggestions-for-useful-ui) on SubT
* [Gazebo classic implementation](https://bitbucket.org/osrf/gazebo/pull-requests/1768/move-the-camera-to-canonical-angles/diff)

**Comment by chapulina** [comment]
This has been implemented as the [view_angle](https://github.com/ignitionrobotics/ign-gazebo/tree/ign-gazebo2/src/gui/plugins/view_angle) widget.
