### ISSUE TITLE
Translation and rotation doesn't work as expected

### ISSUE THREAD

**Issue by Reka-Berci-Hajnovics** [ignitionrobotics/ign-gazebo#345]
In the translation mode the x-axis arrow gets highlighted when I click on the mid of the z-axis arrow. The y-axis and z-axis arrows don't become active after clicking on them.
In the rotation mode a similar thing happens. The roll becomes active after clicking a couple of centimeters below the circle. The other directions do not become active.
I have a fresh installation of ignition gazebo version 3.3.0, foxy, and ubuntu 20.04.
![Screenshot from 2020-09-10 12-45-15](https://user-images.githubusercontent.com/24480017/92721065-cd4f6380-f365-11ea-83aa-2148ed7991ab.png)
![Screenshot from 2020-09-10 12-45-32](https://user-images.githubusercontent.com/24480017/92721069-ce809080-f365-11ea-8de5-e9337a897a3b.png)
![Screenshot from 2020-09-10 12-46-05](https://user-images.githubusercontent.com/24480017/92721071-ce809080-f365-11ea-8fd3-505f66faaa2b.png)
![Screenshot from 2020-09-10 12-46-29](https://user-images.githubusercontent.com/24480017/92721072-cf192700-f365-11ea-8ce2-92f3f12557e8.png)

**Comment by chapulina** [comment]
This sounds related to #147. Are you on a high-dpi display, and are you inside a Docker container?

**Comment by iche033** [comment]
what graphics driver do you have?

**Comment by Reka-Berci-Hajnovics** [comment]
It works now! I'm running Ubuntu 20.04 and a high-dpi display. I've enabled the fractional scaling in the Ubuntu Settings-> Display. I haven't change the scale value, but already by enabling it now I can select the arrow to translate and the circle to rotate the objects in Ignition!

**Comment by chapulina** [comment]
Glad to hear it's solved, I'll close this issue, feel free to reopen if the problem comes back.

It may be a good idea to add a note about this to the [troubleshooting documentation](https://ignitionrobotics.org/docs/citadel/install_ubuntu_src#troubleshooting).

**Comment by iche033** [comment]
thanks for posting the fix. 

just curious, what's the scale value that was set?

**Comment by Reka-Berci-Hajnovics** [comment]
I haven't change the scale value, it was left on 100%. 
This morning I've started ign gazebo shapes.sdf and the translation and rotation weren't working, neither on my built-in screen nor on my external screen.  I've tried to unplug my external screen and then it was working on my built-in screen. 
After plugging in my external screen it still works now. I've tried to stop and relaunch the application and it is still working. I find it a pity that it is not clear what causes this issue. If I'll find something else what might be related to it I'll keep you posted.

**Comment by iche033** [comment]
ok got it, thanks for keeping an eye on it. 

It could be the way we're [querying the scaling factor](https://github.com/ignitionrobotics/ign-rendering/blob/master/src/Utils.cc#L32) in ignition. Let me know if you have more info and I'll see if we can fix this programmatically, thanks.
