### ISSUE TITLE
Tutorial on How-To Transition from Gazebo9 (aka Classic) to Ignition-Gazebo

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gazebo#35]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/35)) by Alfredo Bencomo (Bitbucket: [bencomo](https://bitbucket.org/%7B84891a71-dff2-4b97-8891-9446c16e6f89%7D/), GitHub: [IeiuniumLux](https://github.com/IeiuniumLux)).**

----------------------------------------
Can we add temp placeholder Wiki page in this repo to explain how to transition \(migrate\) from Gazebo9 to Ignition-Gazebo?

The content of that page will be also posted in the [ignitionrobotics.org](http://ignitionrobotics.org) website.

![](https://osrf-migration.github.io/ignition-gh-pages/data/bitbucket.org/repo/8zodKzn/images/3612344952-ignition_logo_org_small.png)

**Comment by chapulina** [comment]
We have lots of resources available now, see https://community.gazebosim.org/t/migration-from-gazebo-classic-to-ignition-gazebo/805
