### ISSUE TITLE
Regression for systems that use rendering

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gazebo#36]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/36)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
# Description 

Until version 2.6.1, it was possible to run multiple systems which accessed the rendering engine. This is how [ros1_ign_point_cloud](https://github.com/osrf/ros1_ign/tree/master/ros1_ign_point_cloud) used to work. But since [pull request #387](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/387), when 2 systems call `ignition::rendering::engine`, the 2nd call crashes with:

`ruby: /var/lib/jenkins/workspace/ogre-2.1-debbuilder/repo/OgreMain/include/OgreSingleton.h:80: Ogre::Singleton<T>::Singleton() [with T = Ogre::LogManager]: Assertion `!msSingle
ton' failed.`

# Steps to Reproduce

I created a simple [example](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/commits/f1d3743a36f217713e515d9d91209483cf6495b5) (861af48c6ac3a9fcf317569461f81cce77cf6131) in a branch which reproduces the issue:

```
hg up rendering_plugin
# follow README instructions
```

Or you could try using `ros1_ign_point_cloud` like this:

`roslaunch ros1_ign_gazebo_demos depth_camera.launch`

**Expected behavior:**  

No crash when running `ign gazebo -s -v 4 rendering_plugin.sdf`

**Actual behavior:**

Crash with the Ogre assertion above.

**Reproduces how often:** 

100%

# Versions

Current `ign-gazebo2` branch (the last release was 2.7.1) crashes. If you build Gazebo from the 2.6.1 tag, you can see there's no crash.

# Additional Information

We could consider the performance improvements from [pull request #387](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/387) to be more important than this use case and no longer support it. But we could also see if it's possible to fix it.

**Comment by chapulina** [comment]
Systems can now safely access the rendering API through the render events, as explained on #596
