### ISSUE TITLE
Add visual clue that Plugins menu is scrollable

### ISSUE THREAD

**Issue by sloretz** [ignitionrobotics/ign-gazebo#368]
(Ignition Citadel 3.3.0) It looks like the Plugins menu is missing the `Transform Control` plugin, but what is actually happening is the vertical size of the Plugins menu is limited and the plugin menu is scrollable.

It would be helpful if there was a visual cue that the menu was scrollable. Maybe an always shown scrollbar, or a gradient at the bottom if there are more choices?

![plugins_button_scrollable](https://user-images.githubusercontent.com/4175662/94046136-23b89b00-fd85-11ea-8eed-45aabecfb93b.png)

Here's what each might look like:

![plugins_button_scrollable_gradient](https://user-images.githubusercontent.com/4175662/94046512-9cb7f280-fd85-11ea-8adf-d44d5699f3ef.png)
![plugins_button_scrollable_always_on_bar](https://user-images.githubusercontent.com/4175662/94046596-c113cf00-fd85-11ea-8d85-72d8e4adf1e0.png)

**Comment by chapulina** [comment]
Yeah I've seen people caught by this before, thinking some plugin wasn't available when all they needed to do was scroll.

I think we can just make the scroll bar always visible. The fix would go on `ign-gui`, I think all that's needed is `policy: ScrollBar.AlwaysOn` [here](https://github.com/ignitionrobotics/ign-gui/blob/22434e23832760130c88d38d7c569a049dcec65c/include/ignition/gui/qml/PluginMenu.qml#L47-L49).

**Comment by chapulina** [comment]
Done on https://github.com/ignitionrobotics/ign-gui/pull/134
