### ISSUE TITLE
View angle plugin buttons are close to the background color, making them hard to differentiate

### ISSUE THREAD

**Issue by sloretz** [ignitionrobotics/ign-gazebo#370]
(Ignition Citadel 3.3.0) I'm having trouble telling which view angle button is which (without hovering over it and reading the tool tip text). I can see the orange face just fine, but the gray edges are very difficult for me to see (could it be my monitor is not calibrated correctly?).

![Screenshot from 2020-09-23 10-42-46](https://user-images.githubusercontent.com/4175662/94049345-ba875680-fd89-11ea-9704-3870cb2ff270.png)

A color picker on the above screenshot shows the background is #fafafa (left half below) while the edge color is #f3f3f3 (right half below)
![background_vs_edge](https://user-images.githubusercontent.com/4175662/94050008-882a2900-fd8a-11ea-8ba7-fb1f3e001dc7.png)

**Comment by chapulina** [comment]
Just use dark mode :innocent:  I'm kidding, we've been trying to make sure all icons show up on both light and dark modes, but I think we just reused those ones from Gazebo-classic for expediency.

I think we could use a darker grey on the lines, and possibly make them thicker? The icons are [here](https://github.com/ignitionrobotics/ign-gazebo/tree/master/src/gui/plugins/view_angle). 

Any thoughts, @ColeOSRF?

**Comment by herobank110** [comment]
Hi, Can I make those adjustments to those icons?

**Comment by chapulina** [comment]
@herobank110 , you're welcome to make the changes and open a pull request, thanks!

**Comment by herobank110** [comment]
I have made darkened variants of the icons for preview below. Any darker than 45 had too little contrast with the dark theme background. Let me know what you think is best.

![view_angle_icon_darken_preview](https://user-images.githubusercontent.com/26686268/96511112-7be49f00-1256-11eb-9467-a6f121b78a92.png)

**Comment by chapulina** [comment]
Thanks, @herobank110 ! 0 is hard to see on the light background on my monitor. I'd go with 25.

**Comment by herobank110** [comment]
please see #426
