### ISSUE TITLE
Dome Transform Control keyboard shortcuts not working

### ISSUE THREAD

**Issue by jennuine** [ignitionrobotics/ign-gazebo#379]
Using Ignition Dome on Ubuntu Focal, I'm not able to enter translate or rotate by typing `T` or `R` shortcuts. I've tried with and without caps lock on. The spacebar works for pause/unpause. I am able to use these modes when selecting them from the top left toolbar and in the Transform Control plugin.

**Comment by chapulina** [comment]
I was talking to @jennuine earlier and I'm not able to reproduce this on my Bionic or Focal setups.

**Comment by JShep1** [comment]
@jennuine Just making my way around to this issue.  Are you still continuing to notice it?

**Comment by jennuine** [comment]
Nope, I updated and rebuilt the workspace and it works now :tada:
