### ISSUE TITLE
Docker images still on bionic, old versions of glvnd don't seem to work with latest versions of nvidia-docker2

### ISSUE THREAD

**Issue by russkel** [ignitionrobotics/ign-gazebo#382]
I was trying to get ignition working via docker (latest version, with nvidia-container-toolkit installed) and I noted that it is still on bionic, which I believe may be interfering with the new nvidia docker support (which doesn't require nvidia-docker2, but nvidia-container-toolkit). 
https://github.com/ignitionrobotics/ign-gazebo/blob/master/docker/Dockerfile.ignition#L7

I am able to get the following to work (please note, the script you include on dockerhub is what I have named `docker-gpu.sh`.
```
./docker-gpu.sh nvidia/opengl:1.2-glvnd-runtime
```
and then installing mesa-utils and running glxgears. I was not able to get glxgears working with your image https://hub.docker.com/r/ignitionrobotics/ignition using the dome tag.

The error messages are your standard:
```
# LIBGL_DEBUG=verbose glxgears
libGL: screen 0 does not appear to be DRI2 capable
libGL: MESA-LOADER: dlopen(/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so)
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /root/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /root/.drirc: No such file or directory.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  43
  Current serial number in output stream:  42
```
I believe this can be fixed by updating to the focal images.

**Comment by russkel** [comment]
Alternatively, you could probably change the base image to `nvidia/opengl:1.2-glvnd-runtime-ubuntu18.04` but given that ROS2 is focal only, it probably makes more sense to get everything on focal.

**Comment by j-rivero** [comment]
Hey @russkel: thanks for ticketing the problem. The different branches named `ign-gazeboX` in this repository links with major versions X and every major version supports different platforms. The current `master` branch would be soon `ign-gazebo4` which is part of Ignition Dome and supported on Focal. So we are good to change, would you mind sending the changes against `master` branch in a PR?

**Comment by russkel** [comment]
Hi @j-rivero, done as you have requested. I have not yet tried these.
