### ISSUE TITLE
Documentation Binary install link is broken

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gazebo#40]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/40)) by Anonymous.**

----------------------------------------
The docs link to https://ignitionrobotics.org/#markdown-header-binary-install

> We recommend following the Binary Install instructions to get up and running as quickly and painlessly as possible.

**Comment by ahcorde** [comment]
- ign-math https://github.com/ignitionrobotics/ign-math/pull/147
 - ign-transport https://github.com/ignitionrobotics/ign-transport/pull/161
