### ISSUE TITLE
Add file extension to file name in double pendulum video record demo

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gazebo#43]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/43)) by John Shepherd (Bitbucket: [John Shepherd](https://bitbucket.org/%7Bc4803212-effe-4921-9323-02cd01b8bc9c%7D/), GitHub: [jshep1](https://github.com/jshep1)).**

----------------------------------------
# Summary

Currently the file extension isn't appended to the end of the typed file name for the `video_record_dbl_pendulum.sdf` example.

# Motivation

This would make the example more user friendly.

**Comment by mabelzhang** [comment]
@mcres will take a stab at this.

**Comment by mcres** [comment]
Yup, let's see if I can solve this one!
