### ISSUE TITLE
Levels are not get loaded correctly on log playbck

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gazebo#46]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/46)) by Ian Chen (Bitbucket: [Ian Chen](https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/), GitHub: [iche033](https://github.com/iche033)).**

The original report had attachments: [state.tlog](https://osrf-migration.github.io/ignition-gh-pages/data/repositories/ignitionrobotics/ign-gazebo/issues/46/attachments/state.tlog)

----------------------------------------
# Description

When seeking to a particular time in the log file, the levels may not be loaded correctly

# Steps to Reproduce

You can skip step 1 and 2 if using the attached `state.tlog` file

1. launch `examples/levels.sdf` with recording enabled

    * `ign gazebo -v 4 --record -r --record_path /tmp/level_log src/ign-gazebo/examples/worlds/levels.sdf --levels`
    
2. publish cmd vel to move the blue vehicle and wait for it to reach the end of the road \(note down this sim time\):

    * `ign topic -t "/model/vehicle_blue/cmd_vel" -m ignition.msgs.Twist -p "linear: {x: 4.0}"`
    
3. Exit gazebo and launch playback:

    * `ign gazebo -v 4 -p /tmp/level_log`
    
4. Seek to the time when the vehicle is at the end of the road, e.g. with the attached `state.tlog`,

    * `ign service -s /world/default/playback/control --reqtype ignition.msgs.LogPlaybackControl --reptype ignition.msgs.Boolean --timeout 5000 --req "seek: {sec: 30}, pause: false"`
    
5. Now seek back to an earlier time when the vehicle was half way through the levels, e.g.

    * `ign service -s /world/default/playback/control --reqtype ignition.msgs.LogPlaybackControl --reptype ignition.msgs.Boolean --timeout 5000 --req "seek: {sec: 10}, pause: false"`
    
6. Notice that the level does not not get loaded properly:

![](https://osrf-migration.github.io/ignition-gh-pages/data/bitbucket.org/repo/8zodKzn/images/2385464638-seek_level.png)
‌

**Expected behavior:**

The middle level should be loaded

**Actual behavior:**

1. The level was not loaded:

**Reproduces how often:**

All the time

# Versions

ign-gazebo 2.0

# Additional Information

related [subt issue](https://bitbucket.org/osrf/subt/issues/311/ign-log-playback-issue#comment-55517711)

**Comment by peci1** [comment]
I think this issue can be closed. I tested it locally on Dome and it works correctly.
