### ISSUE TITLE
Possible memory management issues in DART BoxedLcpConstrainedSolver?

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gazebo#48]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/48)) by Jaldert Rombouts (Bitbucket: [Jaldert](https://bitbucket.org/%7B04334d8c-9f71-470e-abc0-61f12f3b82ff%7D/)).**

The original report had attachments: [conveyor_with_box_crash.gif](https://osrf-migration.github.io/ignition-gh-pages/data/repositories/ignitionrobotics/ign-gazebo/issues/48/attachments/conveyor_with_box_crash.gif), [conveyor_with_box_experiments.tgz](https://osrf-migration.github.io/ignition-gh-pages/data/repositories/ignitionrobotics/ign-gazebo/issues/48/attachments/conveyor_with_box_experiments.tgz)

----------------------------------------
# Prerequisites

* \[X\] Put an X between the brackets on this line if you have done all of the following:

    * Checked the Q&A board for common solutions: [http://answers.gazebosim.org](http://answers.gazebosim.org)
    * Checked that your issue isn't already filed.
    * Checked that there is not already an Ignition package that provides the described functionality: [https://ignitionrobotics.org/libs](https://ignitionrobotics.org/libs)
    

# Description

Thanks for building Ignition Gazebo. I've been experimenting with it and I really like the new architecture.

One of my experiments was building a conveyor model and system plugin. The model consists of a box with a set of rollers \(cylinders\) with revolute joints on top. I've written a custom system plugin to set `JointVelocityCmd`s for all these rollers.

The model runs fine when it is alone in the world - I've left it running for hours without issues.

However, I’m running into issues when I drop a box on top of the running conveyor: I quickly get memory errors like `free(): invalid next size (fast)` and occasionally a segmentation fault or `double free or corruption (out)`. Interestingly, this issue seems to require a combination of the conveyor running and the box moving along it. I tried variations where the model is not running and the box is dropped/placed at similar poses where the simulation crashes and I didn't manage to crash it in this manner.

Taking the GDB backtrace at face value, it seems to be an issue in DART: In particular it seems to happen in `constraint::BoxedLcpConstraintSolver::solveConstrainedGroup(dart::constraint::ConstrainedGroup&) () from /usr/lib/x86_64-linux-gnu/libdart.so.6.10`  \([link](https://gist.github.com/JaldertVicarious/84eaf1c8006e80a4afa30858b296f681#file-backtrace-txt-L8)\)

![](https://osrf-migration.github.io/ignition-gh-pages/data/bitbucket.org/repo/8zodKzn/images/1406188254-crash_with_box.gif)
\(see attachment for high resolution version\).

I was not entirely sure if this issue should be posted here or on `ign-physics` . I’ve posted it here because reproduction requires `ign-gazebo` , but I’m also happy to open the issue elsewhere. 

# Steps to Reproduce

1. Build the `RevoluteConveyorController.so` library

```shell
# Gist with plugin system, and example world SDF
git clone https://gist.github.com/84eaf1c8006e80a4afa30858b296f681.git example

cd example
cmake -H. -Bbuild
cmake --build build

# This step copies plugin to ~/.ignition/gazebo/plugins s.t. dynamic loader can find it.
cmake --build build --target install
```

2\. Run the `conveyor_with_box.sdf` example

```shell
ign gazebo conveyor_with_box.sdf # with gui
# ign gazebo -s -r conveyor_with_box.sdf # headless
```

‌

**Expected behavior:**

The box should drop onto the rollers, move along it and finally fall off the end. The simulation should keep running.

**Actual behavior:**

The box drops, and starts moving along conveyor, then ignition gazebo crashes with memory errors like `free(): invalid next size (fast)` and occasionally a segmentation fault or `double free or corruption (out)`. 

**Reproduces how often:**

Always. There is variation in the exact timing to crash \(looking at the number of simulation iterations\) as well as the exact error \(see detailed description above\).

# Versions

* OS: Ubuntu 18.04 Bionic
* Ignition Version: Clean build of all Ignition Citadel packages, following [install\_ubuntu\_src](https://ignitionrobotics.org/docs/citadel/install_ubuntu_src). 

# Additional Information

* Virtual machine: No, running native.

‌

‌

‌

**Comment by azeey** [comment]
I believe this has been fixed by https://github.com/azeey/dart/pull/6, which is the fork of DART used by ign-gazebo. I ran all the SDF files in `conveyor_with_box_experiments.tgz` without any failures. Thank you for creating a systematic set of configurations for testing this.
