### ISSUE TITLE
Transform Controller Markers Behind Environment Models

### ISSUE THREAD

**Issue by ibrahimkakbar** [ignitionrobotics/ign-gazebo#496]
The GUI Transform Control displays of a robot model for the linear/rotational transformations are behind the world environment and only appear on the robot model. I have attached images of:

-  a regular version which shows some clipping on the rotation circles
- a zoomed in version to show the complete rotation circles displayed on the robot model
- a zoomed out version to show the bands disappear and only be visible in open space
![regular_view_with_band_clippings](https://user-images.githubusercontent.com/27082910/102533264-2d475b80-4073-11eb-80f8-ffb465066b03.png)
![zoomed_in_rotational_bands](https://user-images.githubusercontent.com/27082910/102533124-fa9d6300-4072-11eb-82c6-26e08ae99b09.png)
![zoomed_out_rotation](https://user-images.githubusercontent.com/27082910/102533131-fc672680-4072-11eb-9781-f6da4d193648.png)

**Comment by chapulina** [comment]
Thanks for the issue. There's probably some property of the cave materials that is making it be rendered above the GUI tools. The fix may end up being in `ign-rendering`, but it's fine to keep tracking this here.

**Comment by angelacmaio** [comment]
Seconding this one. It's quite difficult to build worlds with the GUI when you can't count on the arrows. I did not see this issue with any materials displaying over the arrows until the switch from Blueprint to Dome.

**Comment by chapulina** [comment]
I did some tests and it looks like the markers, and probably anything with `IGN_VISIBILITY_GUI` don't show through any PBR materials. It's easy to reproduce with [this model](https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Rescue%20Randy):

![image](https://user-images.githubusercontent.com/5751272/110185924-88623200-7dc8-11eb-9959-58b2b14bc176.png)

@iche033 , any guidance on how to fix this?

**Comment by iche033** [comment]
here's a fix in https://github.com/ignitionrobotics/ign-rendering/pull/266
