### ISSUE TITLE
OneTimeChange components update and SceneBroadcaster performance

### ISSUE THREAD

**Issue by luca-della-vedova** [ignitionrobotics/ign-gazebo#529]
We have an environment in which we need specific components, other than the standard [Pose](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo4/src/systems/scene_broadcaster/SceneBroadcaster.cc#L291-L297), to be updated at every iteration, specifically [TrajectoryPose](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo4/include/ignition/gazebo/components/Pose.hh#L46) for actors since we want to control their movement in a plugin.
If the component doesn't have [OneTimeChange](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo4/include/ignition/gazebo/Types.hh#L75) specified some updates will be missed and the components will not be updated at every iteration (i.e. actor movements will be "jerky"). On the other hand, if any component is set to OneTimeChange [the whole state of the simulation](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo4/src/systems/scene_broadcaster/SceneBroadcaster.cc#L286-L290) will be serialized and published, causing a major performance loss.

I thought of at least three possible ways to deal with the issue:

1. Exposing critical components to userspace, with an API where a user can specify (in SDF or a plugin) "For this specific world, I need component X to be accurate (i.e. `Temperature` if they want to simulate temperature, `AnimationTime` if they want smooth animations).
2. Making `OneTimeChange` only update the changed component and not the whole simulation state.
3. Adding a new `OneTimeChange` type that marks only a specific component as changed (i.e. `OneTimeComponentChange`), to preserve the current behavior.

**Comment by chapulina** [comment]
Since #544 all `PeriodicChange`s are published regularly, not just pose. So periodic components don't need to be marked as `OneTimeChange`s to be published.
