### ISSUE TITLE
Support particle effects

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-gazebo#558]
Ignition Rendering supports custom particle emitters since Dome, see [Ignition Rendering: Particles](https://ignitionrobotics.org/api/rendering/4.1/particles.html).

Users should already be able to add such particles to their simulations through a custom plugin, but we should offer a convenient way of adding these particles to their Ignition Gazebo simulation from an SDF file. The particles should show up on both server and client scenes, and sensors like cameras and lidars should observe them in a reasonable way.

The beginning of the implementation is in https://github.com/ignitionrobotics/ign-gazebo/pull/516.

**Comment by adlarkin** [comment]
Can we close this? #516 has been merged.
