### ISSUE TITLE
Auto-load a subset of world plugins unless user opts-out

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gazebo#57]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/57)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
The need to specify all plugins to be loaded by simulation though an SDF file makes it more complicated and verbose to write these files. We could make the user's life easier by automatically loading the most common plugins.

It would be ideal to give users an option to opt-out from these plugins, in case they want to load a complete different set of plugins. It would also be nice to let users append to the list of most common plugins, instead of needing to repeat the entire list just to add a new one.

[Pull request #537](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/537) started this work but couldn't be merged in time for GitHub migration, so we can reopen it there.

**Comment by mjcarroll** [comment]
Closed by #281

**Comment by azeey** [comment]
Looks like automatic loading is disabled if there are any systems at all, even systems attached to models. Is that intentional?

**Comment by chapulina** [comment]
> Looks like automatic loading is disabled if there are any systems at all, even systems attached to models. Is that intentional?

We're not making a distinction about what entity the plugin is attached to. Honestly I think we didn't think of that specific case. Maybe it makes sense to limit it to world plugins.
