### ISSUE TITLE
Optional physics features

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gazebo#58]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/58)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
Currently, all features used by the physics system are required to load a physics engine. In the interest of supporting multiple physics engines with different sets of features, the physics system can be refactored so that some features are optional. Optional features are just skipped if not supported by a physics engine, while required features prevent the engine from being loaded.

[Pull request #573](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/573) started work on this but couldn't be merged in time for GitHub migration. We'll reopen the PR there.

**Comment by chapulina** [comment]
@mxgrey made a comment on the pull request after the freeze which didn't make it into the [back up](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/573/page/1?slug=optional-physics-features), so I'll copy it here for it not to get lost:

---

Michael Grey commented on pull request #573:
--
Optional physics features

I’m not 100% clear on why an additional RequestFeatures would be needed, but the runtime cost of it should be unnoticeable if the casted entities are being cached. Either way, this  is probably a premature optimization concern. I’d say whenever there’s a  need in the future to audit the compilation times, this would be a  prime candidate to look at.

---

I can respond properly once we're done with the migration.

**Comment by chapulina** [comment]
> I’m not 100% clear on why an additional RequestFeatures would be needed

We need `DetachableJointFeatureList` for 2 entities: the child link and the detachable joint. The joint is created from the `childLink->AttachFixedJoint` call, so it inherits all features from the link. After it's created, we need to call some "core" joint features, and also store the joint in the global joint map. For those, `MinimumFeatureList` is necessary. If `DetachableJointFeatureList` doesn't include `MinimumFeatureList`, we need to make a `RequestFeatures` call to cast it.

> Either way, this is probably a premature optimization concern. I’d say whenever there’s a need in the future to audit the compilation times, this would be a prime candidate to look at.

+1

**Comment by chapulina** [comment]
Now that #62 has been merged, all that's missing is to add support for TPE. There's initial work on the `chapulina/tpe` branch which needs to be cleaned up.
