### ISSUE TITLE
simulating glTF file in ignition gazebo

### ISSUE THREAD

**Issue by addy1997** [ignitionrobotics/ign-gazebo#655]
I am trying to simulate a walking deer for motion tracking in the ignition gazebo. Since I couldn't find a suitable Collada (.dae) file, I thought of simulating the .glTF file in the ignition gazebo. Is there a way of doing so?

**Comment by chapulina** [comment]
We don't have support for glTF yet, see https://github.com/ignitionrobotics/ign-common/issues/173.

We'd be willing to take a GSoC intern to work on this, see our [GSoC project list](https://github.com/osrf/osrf_wiki/wiki/GSoC#add-support-for-loading-more-mesh-formats-in-gazebo).

Closing this in favor of the issue above.
