### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by FirefoxMetzger** [ignitionrobotics/ign-gazebo#663]
The documentation page: https://ignitionrobotics.org/api/gazebo/4.0/resources.html has a broken link in the section *Ignition GUI plugins*. The link ` GUI config files` points to the 3.0 version, which returns a 404 error. Changing the link to
https://ignitionrobotics.org/api/gui/4.0/config.html
resolves this problem.

I don't know where the documentation lives, but if somebody provides me with a pointer, I will submit a small PR to fix it.

**Comment by ahcorde** [comment]
Tutorials live [here](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo4/tutorials/) in particular -> [resources](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo4/tutorials/resources.md)

Happy to review the PR
