### ISSUE TITLE
distortion and irregularities in simulation in ignition gazebo 4

### ISSUE THREAD

**Issue by addy1997** [ignitionrobotics/ign-gazebo#679]
## Environment
* OS Version: Ubuntu 18.04 (Virtual Machine)
* Source or binary build?
 binary installed (version below)
```
adwaitnaik@ubuntu:~$ ign gazebo -v
[Msg] Ignition Gazebo GUI    v4.6.0
[Msg] Ignition Gazebo Server v4.6.0

```
## Description
* Expected behavior: The animal should simulate normally as it does in the Blender (version 2.8). Please see the images below

![image](https://user-images.githubusercontent.com/29406906/110727718-cb495d00-8241-11eb-972d-5041698f19c3.png)

![image](https://user-images.githubusercontent.com/29406906/110727768-e0be8700-8241-11eb-8e2d-32c6bc9a77f6.png)

* Actual behavior: File format 

* terminal throws the following error 

`[GUI] [Err] [RenderUtil.cc:879] invalid animation update data`

* The animal is distorted and disoriented in the ign gazebo (please see the image below)

![image](https://user-images.githubusercontent.com/29406906/110727986-427ef100-8242-11eb-9cf1-a2bdd02a8d71.png)

![image](https://user-images.githubusercontent.com/29406906/110728002-47dc3b80-8242-11eb-9412-ddda7964749d.png)

## Steps to reproduce
Link to the files below (files are in .dae and .sdf format)

* [model file](https://drive.google.com/file/d/1XlaegGLUggGMK_G6P6IJIUK0aAyyb1QM/view?usp=sharing)
* [collada file](https://drive.google.com/file/d/1mTxGHydZLFmnJnfgccide-QnJjJJvYV2/view?usp=sharing)

Thanks

**Comment by chapulina** [comment]
Cool model :deer: 

We have some actors that were created on Blender and animate correctly on Ignition, like [Male visitor](https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Male%20visitor). The tricky part is that it usually takes us some back-and-forth with various Blender export settings until we get the models to work correctly on Ignition. Once we figure out the fail-proof export settings, we'll write a tutorial for the community.

Meanwhile, I think you could try changing some settings when you export from Blender. You could also try exporting the animation to BVH to see if that helps. It's also possible that our [ColladaLoader](https://github.com/ignitionrobotics/ign-common/blob/ign-common3/graphics/src/ColladaLoader.cc) may need some tweaks to properly support that model.

Please let us know if you get it to work!

**Comment by addy1997** [comment]
https://answers.gazebosim.org/question/26731/irregularities-in-simulation-in-ignition-gazebo-4/

**Comment by ebasatemesgen** [comment]
Hi, would you be able to share your 3D model. It will be great to test that out in the new gazebo
