### ISSUE TITLE
GUI Commands Tutorial

### ISSUE THREAD

**Issue by JShep1** [ignitionrobotics/ign-gazebo#70]
Create tutorials documenting the GUI tools currently available:

* Key bindings (similar to Gazebo's hotkeys http://gazebosim.org/hotkeys.html)
* Transform control
* View angle widget
* Align tool
* Model insertion from Fuel

I imagine we can do a first pass just to make sure they're documented, and improve on them later. It's better to have some documentation than none, so we don't need to go too crazy at first.

**Comment by maryaB-osr** [comment]
https://github.com/ignitionrobotics/docs/pull/10

I opened a PR for this over in /docs. I guess we can leave this issue here and just link them?

**Comment by chapulina** [comment]
They're live:

https://ignitionrobotics.org/docs/blueprint/gui

https://ignitionrobotics.org/docs/citadel/gui
