### ISSUE TITLE
code to fetch ign gazebo's major version

### ISSUE THREAD

**Issue by addy1997** [ignitionrobotics/ign-gazebo#704]
What is the code to fetch ign gazebo's major version? In Gazebo, we can simply write this 

` #if GAZEBO_MAJOR_VERSION < 6`

to impose a condition on the plugin to work **only** for a particular version.

**Comment by scpeters** [comment]
see the definition of `IGNITION_GAZEBO_VERSION` in the `config.hh` header file, which is configured from the following template:

* https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo4/include/ignition/gazebo/config.hh.in#L8

**Comment by chapulina** [comment]
@addy1997 , I'm closing this now, please let us know if that didn't work for you,
