### ISSUE TITLE
No output from ign topic when running gpu_lidar examples

### ISSUE THREAD

**Issue by ammaar8** [ignitionrobotics/ign-gazebo#726]
## Environment
* OS Version: Ubuntu 18.04
* Source or binary build?
  binary version 5.0.0~pre1
  

## Description
* Expected behavior: In [gpu_lidar_retro_values_sensor.sdf](https://github.com/ignitionrobotics/ign-gazebo/blob/4ea19561061fece12d09027c226d11cb892ace49/examples/worlds/gpu_lidar_retro_values_sensor.sdf) demo file, on running the example running `ign topic -e -t /lidar` in a different terminal should print lidar messages. 
* Actual behavior: Running `ign topic -e -t /lidar` returns nothing. Even `ign topic -l` returns nothing. I can get the lidar visualization using the visualize lidar plugin using the `lidar` topic. 

## Steps to reproduce

1. Run `ign gazebo gpu_lidar_retro_values_sensor.sdf` in a terminal and play the simulation
2. In a different terminal run `ign topic -e -t /lidar`
3. In another terminal run `ign topic -l`

**Comment by chapulina** [comment]
I can't reproduce this issue with the latest Ignition Edifice debs. Is this still an issue for you, @ammaar8 ?

**Comment by ammaar8** [comment]
I tried running it again but still have the same issue. It could be something related to my system. I'm switching to focal so won't be able to test it going forward.

**Comment by chapulina** [comment]
Oh ok, so this happens only on Bionic?

I'd be interested to learn if you had more than one Ignition version installed, which can be checked with `ign topic --versions`.

**Comment by ammaar8** [comment]
Just tested on Focal and it works fine. 

I checked and turns out I do have two versions installed `4.0.0` and `10.0.0`. Ran with `--force-version 10.0.0` at it works! Sorry for all the trouble.

**Comment by chapulina** [comment]
Glad to hear it works!
