### ISSUE TITLE
Random velocity and gimbal small2d plugin

### ISSUE THREAD

**Issue by addy1997** [ignitionrobotics/ign-gazebo#776]
I have implemented few plugins like the gimbal small 2d (model) plugin and the random velocity plugin. Referring to this [doc](https://ignitionrobotics.org/docs/edifice/comparison), I decided to raise an issue to know whether it will be suitable to contribute?

I have managed to compile the plugins successfully and generate the lib.so file. Also, I have tested the link plugin which works fine.

**Comment by ahcorde** [comment]
Hi @addy1997,

I checked this morning this PR https://github.com/ignitionrobotics/ign-gazebo/pull/775, which is already closed, but the random velocity plugin has some ROS dependencies. In that case this plugin should live in [ign_ros](https://github.com/ignitionrobotics/ros_ign/). but you can re-write the plugin to make it only Ignition compatible.
