### ISSUE TITLE
Gimbal rolls in a bizarre manner when simulated

### ISSUE THREAD

**Issue by addy1997** [ignitionrobotics/ign-gazebo#808]
Hello there,

While testing the gimbalsmall2d plugin in the ignition, I observed this (gif attached below)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/29406906/117295970-20949a00-ae92-11eb-9992-3007274c0b04.gif)

I have ported the plugin and changed the sdf file according to the ` sdf migration tutorial`. The sdf file can be found [here](https://github.com/addy1997/peding/blob/main/gimbal.sdf).

## Expected behavior

I was expecting the `tilt joint` of `gimbal` to move instead of the whole `gimbal rolling`. 

## Steps to reproduce the error/phenomenon

All the files {source, main, and CMakeLists.txt} can be found here in this [folder](https://drive.google.com/drive/folders/13CRPHa1de2-7sf0_0ph4VaR5rz9eatJ4?usp=sharing) and meshes can be found [here](https://github.com/addy1997/peding/tree/main/meshes). Please download all the files along with the folder.

Also, here are the instructions to generate `library(.so)` file 

```
cd gimbal

mkdir build

cd build

cmake ..

make 

```
to export the path

``` 
export IGN_GAZEBO_SYSTEM_PLUGIN_PATH=`pwd`/build
```
**Caveat** (only for ubuntu 18.04 and above)

Sometimes, the path isn't exported properly. In such case, please use this command

```
sudo cp libGimbalSmall.so /usr/lib/x86_64-linux-gnu/ign-gazebo-5/plugins
```
Thanks

**Comment by chapulina** [comment]
This looks like a problem with the collision shape. You can debug it by right-clicking the model and choosing to view collisions.

I'll close this issue, because I believe this isn't a bug in Ignition. Please direct questions to [Gazebo Answers](https://answers.gazebosim.org) if you're not sure they're bugs, thanks.
