### ISSUE TITLE
Support `gzerr` and friends

### ISSUE THREAD

**Issue by gerkey** [ignitionrobotics/ign-gazebo#82]
In the course of migrating a plugin from Gazebo to Ignition (#80), one of the seemingly unnecessary changes was to replace `gzerr` with `ignerr` (same for the `warn`, `log`, and `dbg` versions).

Given that the functionality and signature are seemingly unchanged, it would be nice if `gzerr` and friends just kept working.

If there's a technical challenge to continuing to allow the old names (@chapulina mentioned that there are use cases where `gzerr` and `ignerr` are mixed in the same code), then I'm OK with calling this wontfix, given that the cost to the user is a simple search-replace.

**Comment by chapulina** [comment]
Thanks for bringing this up.

> I'm OK with calling this wontfix, given that the cost to the user is a simple search-replace.

We'll go with this for now, and we can revisit if it becomes a common pain point to many migrating users.

---

One thing we should consider more generally would be some migration script that does various search-and-replace tasks, see #98. As a reference, [here](https://github.com/awslabs/ros2-migration-tools/blob/9a85a3bd6ca6e2ef3130cb26f2e161a3df9c57dc/mapping/master_mappings.json#L157-L166)'s a script which, among many things, migrates the console logging macros from ROS 1 to ROS 2.
