### ISSUE TITLE
Test Regression: INTEGRATION_save_world

### ISSUE THREAD

**Issue by mjcarroll** [ignitionrobotics/ign-gazebo#852]
## Environment
* OS Version: `bionic`
* Source or binary build? `main` / `ign-gazebo6`

## Description

Between `ign-gazebo5` and `main`, we have introduced a test regression that causes `INTEGRATION_save_world/SdfGeneratorFixture/WorldWithModelsSpawnedAfterLoad` to fail with error: 

```
Error [parser.cc:574] Error parsing XML from string: Error=XML_ERROR_MISMATCHED_ELEMENT ErrorID=16 (0x10) Line number=45: XMLElement name=data-string
/home/mjcarroll/workspaces/ign_fortress/src/ign-gazebo/test/integration/save_world.cc:155: Failure
Value of: err.empty()
  Actual: false
Expected: true
/home/mjcarroll/workspaces/ign_fortress/src/ign-gazebo/test/integration/save_world.cc:157: Failure
Expected: (nullptr) != (world), actual: (nullptr) vs NULL
```

## Output

I output the SDF file to inspect what is being parsed in both versions, here is snipped to the relevant section:

`ign-gazebo5`
```
    <model name='spawned_model'>
      <link name='link'>
        <visual name='visual'>
          <geometry>
            <sphere>
              <radius>1</radius>
            </sphere>
          </geometry>
          <plugin name='__default__' filename='__default__'/>
        </visual>
      </link>
      <plugin name='__default__' filename='__default__'/>
      <pose>10 0 -1e-05 0 -0 0</pose>
    </model>
```

`ign-gazebo6`
```
    <include>
      <uri>file://<data-string></uri>
      <name>spawned_model</name>
      <pose>10 0 -1e-05 0 -0 0</pose>
    </include>
```

**Comment by azeey** [comment]
This should be fixed by https://github.com/osrf/sdformat/pull/582

**Comment by chapulina** [comment]
It looks like we may just need a forward-port, starting here: https://github.com/osrf/sdformat/pull/593

**Comment by azeey** [comment]
Yup, I'm working on the forward-port.

**Comment by azeey** [comment]
Fixed by https://github.com/ignitionrobotics/sdformat/pull/627
