### ISSUE TITLE
New release for Edifice

### ISSUE THREAD

**Issue by Tobias-Fischer** [ignitionrobotics/ign-gazebo#885]
Hi there,
We are in the process of packaging Edifice in conda-forge (see https://github.com/conda-forge/libignition-gazebo-feedstock/pull/5). At the moment Windows fails, which I think is because https://github.com/ignitionrobotics/ign-gazebo/pull/758 is not contained in the 5.0.0 release. Any chance to release a new version so we don't need to apply patches?

/cc @traversaro

**Comment by chapulina** [comment]
Sure thing, I'll work on a release as soon as https://github.com/ignitionrobotics/ign-gazebo/pull/877 is in :+1:

**Comment by chapulina** [comment]
The GitHub release is out, debs in the oven: https://build.osrfoundation.org/job/ign-gazebo5-debbuilder/

**Comment by Tobias-Fischer** [comment]
Many thanks @chapulina!
