### ISSUE TITLE
Load worlds from Fuel

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-gazebo#89]
Ignition Fuel hosts world files as well as models:

https://app.ignitionrobotics.org/fuel/worlds

Ignition Gazebo doesn't have a nice way of loading them yet though. It would be nice to support loading them from the command line like:

`ign gazebo https://fuel.ignitionrobotics.org/1.0/openrobotics/worlds/demo`

We could also consider moving the [example worlds](https://github.com/ignitionrobotics/ign-gazebo/tree/master/examples/worlds) to Fuel.

**Comment by chapulina** [comment]
Just summarizing some of the conversations that happened around this issue:

* Worlds on Fuel are directories, not single files
* Unlike models, which have `model.config`, we don't have a standard way of setting metadata for worlds
* For now, users should pass the world root directory URL and we'll load the first `.sdf` file found
* We need to update the [worlds we currently have on Fuel](https://app.ignitionrobotics.org/fuel/worlds) to use `.sdf` instead of `.world`. As a first step, we could have both files there to avoid breaking CI.
* Going forward, we're considering supporting metadata for worlds. @nkoenig will work on a short design document for that.

**Comment by JShep1** [comment]
Both PRs resolving this issue can be found at https://github.com/ignitionrobotics/ign-gazebo/pull/274 and https://github.com/ignitionrobotics/ign-launch/pull/43

**Comment by JShep1** [comment]
Closing this issue as the PR fixing the issue (https://github.com/ignitionrobotics/ign-gazebo/pull/274) has been merged
