### ISSUE TITLE
While using contact sensor, the simulation stuck when contact happens

### ISSUE THREAD

**Issue by 0smile** [ignitionrobotics/ign-gazebo#997]
## Environment
* OS Version: Ubuntu20.04
* Source or binary build?
  Binary, Fortress

  
## Description
I'm just testing the example world contact_sensor.sdf, I found out that when the ball hit the ground, the simulation stuck. The simulation time and real time are both barely moving, but the simulation is still working, because the iterations is still increasing slowly. 
After waiting for some time, the simulation shutdown itself and the terminus output some log, which I've added below.
* Expected behavior: The simulation should continue in regular rate while the ball hit the ground
* Actual behavior: The simulation stuck when contact happens

## Steps to reproduce
I did no other action except input "ign gazebo contact_sensor.sdf", and click the start button.

## Output
ODE INTERNAL ERROR 1: assertion "aabbBound >= dMinIntExact && aabbBound < dMaxIntExact" failed in collide() [collision_space.cpp:460]
/usr/lib/ruby/ignition/cmdgazebo6.rb:432: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

-- Control frame information -----------------------------------------------
c:0007 p:---- s:0059 e:000058 CFUNC  :call
c:0006 p:0016 s:0054 e:000053 METHOD /usr/lib/ruby/ignition/cmdgazebo6.rb:432
c:0005 p:0060 s:0048 e:000047 BLOCK  /usr/lib/ruby/ignition/cmdgazebo6.rb:468 [FINISH]
c:0004 p:---- s:0045 e:000044 CFUNC  :fork
c:0003 p:0674 s:0041 e:000040 METHOD /usr/lib/ruby/ignition/cmdgazebo6.rb:464
c:0002 p:0683 s:0020 E:000c40 EVAL   /usr/bin/ign:275 [FINISH]
c:0001 p:0000 s:0003 E:001f70 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/bin/ign:275:in `<main>'
/usr/lib/ruby/ignition/cmdgazebo6.rb:464:in `execute'
/usr/lib/ruby/ignition/cmdgazebo6.rb:464:in `fork'
/usr/lib/ruby/ignition/cmdgazebo6.rb:468:in `block in execute'
/usr/lib/ruby/ignition/cmdgazebo6.rb:432:in `runGui'
/usr/lib/ruby/ignition/cmdgazebo6.rb:432:in `call'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f4730132191 RBP: 0x00007f470b7fd6f0 RSP: 0x00007f470b7fd6a0
 RAX: 0x00007f46fc26c958 RBX: 0x00007f470b7fd6c0 RCX: 0x0000000000000004
 RDX: 0x00007f46fc26c920 RDI: 0x61756e6574746120 RSI: 0x00007f46fcc34ce0
  R8: 0x0000000000000003  R9: 0x0000000000000000 R10: 0x00007f46fc0008d0
 R11: 0x00007f46fc000080 R12: 0x00007f46fc723ea0 R13: 0x00007f470b7fd810
 R14: 0x00007f46fc723ea0 R15: 0x00007f472eaa05e8 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------

**Comment by 0smile** [comment]
This bug is still not fixed on my computer. Really hope to it can be fixed in the official released Fortress.

**Comment by diegoferigo** [comment]
Same thing occurs in my setup. It's a [particular setup](https://github.com/diegoferigo/development-iit/blob/feature/fortress/Conda/Dockerfile) with a conda environment enabled containing the dependencies, and Fortress built with colcon. As described in the downstream issue I linked above, it does not seem that the whole simulation gets stuck, just the GUI.

**Comment by 0smile** [comment]
> Same thing occurs in my setup. It's a [particular setup](https://github.com/diegoferigo/development-iit/blob/feature/fortress/Conda/Dockerfile) with a conda environment enabled containing the dependencies, and Fortress built with colcon. As described in the downstream issue I linked above, it does not seem that the whole simulation gets stuck, just the GUI.

Yes, it seems that the simulation is still running, because I can see the message be printing as the normal refresh rate in the ignition topic. By the way, really like your gym ignition work!

**Comment by diegoferigo** [comment]
I ported to a source-based fortress setup the patch of #1048 and I confirm that it fixes the problem for me, thanks @azeey!

**Comment by azeey** [comment]
Fixed by https://github.com/ignitionrobotics/ign-gazebo/pull/1062
